<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-S76SA9N" failures="2" tests="3" name="runner.pengajuan.HRISDateCountRunner" time="56.495" errors="0" timestamp="2022-07-07T14:34:17 ICT" skipped="0">
  <testcase classname="runner.pengajuan.HRISDateCountRunner" name="runScenario" time="20.620"/>
  <system-out/>
  <testcase classname="runner.pengajuan.HRISDateCountRunner" name="runScenario" time="18.864">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at definitions.data.HRISBukcetDataDefine.countEquals(HRISBukcetDataDefine.java:265)
at ✽.Count equals 3(file:///D:/Project/Java/TestNG/HRIS/src/test/resources/features/PagePengajuan/HRISCutiDateCount.feature:129)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.pengajuan.HRISDateCountRunner" name="runScenario" time="17.011">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at definitions.data.HRISBukcetDataDefine.countEquals(HRISBukcetDataDefine.java:265)
at ✽.Count equals 0(file:///D:/Project/Java/TestNG/HRIS/src/test/resources/features/PagePengajuan/HRISCutiDateCount.feature:129)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- runner.pengajuan.HRISDateCountRunner -->
