<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-S76SA9N" failures="1" tests="3" name="runner.pengajuan.HRISInvalidRunner" time="43.702" errors="0" timestamp="2022-07-08T15:34:27 ICT" skipped="0">
  <testcase classname="runner.pengajuan.HRISInvalidRunner" name="runScenario" time="12.847"/>
  <system-out/>
  <testcase classname="runner.pengajuan.HRISInvalidRunner" name="runScenario" time="17.005"/>
  <system-out/>
  <testcase classname="runner.pengajuan.HRISInvalidRunner" name="runScenario" time="13.850">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at definitions.data.HRISBukcetDataDefine.noteFieldError(HRISBukcetDataDefine.java:234)
at âœ½.Show error note field(file:///D:/Project/Java/TestNG/HRIS/src/test/resources/features/PagePengajuan/HRISInvalidData.feature:28)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- runner.pengajuan.HRISInvalidRunner -->
